name: C/C++ CI

on:
  push:
      branches: [ master ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - run: sudo apt install -y build-essential
        # - name: configure
        # - run: ./configure
        - run: mkdir build && cd build && cmake ../
        - run: make
        - run: ./test